apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cluster-api.fullname" . }}-aggregated-manager-role
  labels:
    cluster.x-k8s.io/provider: cluster-api
  {{- include "cluster-api.labels" . | nindent 4 }}
rules: []