apiVersion: v1
kind: Service
metadata:
  name: {{ include "cluster-api.fullname" . }}-webhook-service
  labels:
    cluster.x-k8s.io/provider: cluster-api
  {{- include "cluster-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type }}
  selector:
    cluster.x-k8s.io/provider: cluster-api
  {{- include "cluster-api.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.webhookService.ports | toYaml | nindent 2 -}}