{{- $root := . -}}
{{- if .Values.deployments }}
{{- range $name, $key := .Values.deployments }}
{{- include "hpa" ( list $root $name $key ) }}
{{- end }}
{{- end }}
{{- if .Values.statefulsets }}
{{- range $name, $key := .Values.statefulsets }}
{{- include "hpa" ( list $root $name $key) }}
{{- end }}
{{- end }}

{{- define "hpa" -}}
{{- $root := index . 0 }}
{{- $name := index . 1 }}
{{- $key := index . 2 }}
{{- $hpa := $key.autoscaling }}
{{- if $hpa.enabled }}
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "common.fullname" $root }}-{{ $name | replace "_" "-"  }}
  namespace: {{ $root.Release.Namespace }}
{{- with $hpa.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
{{ include "common.labels.standard" $root | indent 4 }}
{{- with $hpa.labels }}
{{ toYaml .| indent 4 }}
{{- end }}
{{- with $key.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "common.fullname" $root }}-{{ $name | replace "_" "-"  }}
  minReplicas: {{ $hpa.minReplicas }}
  maxReplicas: {{ $hpa.maxReplicas }}
  metrics:
  {{- if $hpa.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $hpa.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if $hpa.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $hpa.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}
{{- end }}
