{{- if .Values.regcred }}
{{- if .Values.regcred.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels.standard" . | indent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "monochart.imagePullSecret.generate" . }}
{{- end }}
{{- end }}