controllerManager:
  manager:
    image:
      repository: k8s.gcr.io/cluster-api/kubeadm-control-plane-controller
    args:
      clusterTopology: false
  replicas: 1
webhookService:
  ports:
  - port: 443
    targetPort: webhook-server
  type: ClusterIP
