controllerManager:
  manager:
    image:
      repository: gcr.io/k8s-staging-cluster-api/kubeadm-control-plane-controller
      tag: main
  replicas: 1
webhookService:
  ports:
  - port: 443
    targetPort: webhook-server
  type: ClusterIP
