apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "cluster-api-provider-hetzner.fullname" . }}-mutating-webhook-configuration
  labels:
  {{- include "cluster-api-provider-hetzner.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: cluster-api-provider-hetzner-system/caph-serving-cert
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: caph-webhook-service
      namespace: cluster-api-provider-hetzner-system
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta1-hcloudmachine
  failurePolicy: Fail
  name: mutation.hcloudmachine.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - hcloudmachines
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: caph-webhook-service
      namespace: cluster-api-provider-hetzner-system
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta1-hcloudmachinetemplate
  failurePolicy: Fail
  name: mutation.hcloudmachinetemplate.infrastructure.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - hcloudmachinetemplates
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: caph-webhook-service
      namespace: cluster-api-provider-hetzner-system
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta1-hetznercluster
  failurePolicy: Fail
  name: mutation.hetznercluster.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - hetznerclusters
  sideEffects: None