apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "cluster-api-provider-hetzner.fullname" . }}-serving-cert
  labels:
  {{- include "cluster-api-provider-hetzner.labels" . | nindent 4 }}
spec:
  dnsNames:
  - caph-webhook-service.{{ .Release.Namespace }}.svc
  - caph-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: '{{ include "cluster-api-provider-hetzner.fullname" . }}-selfsigned-issuer'
  secretName: webhook-server-cert