apiVersion: v1
kind: Service
metadata:
  name: {{ include "cluster-api-provider-hetzner.fullname" . }}-webhook-service
  labels:
  {{- include "cluster-api-provider-hetzner.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type }}
  selector:
    control-plane: caph-controller-manager
  {{- include "cluster-api-provider-hetzner.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.webhookService.ports | toYaml | nindent 2 -}}