controllerManager:
  manager:
    image:
      repository: quay.io/syself/cluster-api-provider-hetzner
    resources:
      limits:
        cpu: 100m
        memory: 30Mi
      requests:
        cpu: 100m
        memory: 20Mi
  replicas: 1
managerConfig:
  controllerManagerConfigYaml:
    health:
      healthProbeBindAddress: :8081
    leaderElection:
      leaderElect: true
      resourceName: hetzner.cluster.x-k8s.io
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
webhookService:
  ports:
  - port: 443
    targetPort: 9443
  type: ClusterIP
