apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
{{- with .Values.controller.service.annotations }}
  annotations:
{{- toYaml . | indent 4 }}
{{- end }}
  labels:
{{ include "common.labels.standard" . | indent 4 }}
{{- with .Values.controller.service.labels }}
{{- toYaml . | indent 4 }}
{{- end }}
spec:
  selector:
    component: controller
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- include "common.labels.selector" . | nindent 4 }}
    {{- with .Values.controller.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  ports:
    - port: 9189
      name: metrics
      targetPort: metrics