apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}node-metrics
  namespace: {{ .Release.Namespace }}
{{- with .Values.node.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
{{ include "common.labels.standard" . | indent 4 }}
{{- with .Values.node.service.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  selector:
    component: node
    {{ include "common.labels.standard" . | nindent 4 }}
    {{- include "common.labels.selector" . | nindent 4 }}
    {{- with .Values.node.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  ports:
    - port: 9189
      name: metrics
      targetPort: metrics