{{- if .Values.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "common.fullname" . }}-controller
  namespace: {{ .Values.prometheus.serviceMonitor.namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.prometheus.serviceMonitor.labels }}
{{ toYaml .Values.prometheus.serviceMonitor.labels | indent 4}}
{{- end }}
spec:
  endpoints:
  - port: metrics
  namespaceSelector:
    matchNames:
    - {{.Release.Namespace}}
  selector:
    matchLabels:
      component: controller
      {{- include "common.labels.standard" . | nindent 6 }}
      {{- include "common.labels.selector" . | nindent 6 }}
      {{- with .Values.controller.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "common.fullname" . }}-node
  namespace: {{ .Values.prometheus.serviceMonitor.namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.prometheus.serviceMonitor.labels }}
{{ toYaml .Values.prometheus.serviceMonitor.labels | indent 4}}
{{- end }}
spec:
  endpoints:
  - port: metrics
  namespaceSelector:
    matchNames:
    - {{.Release.Namespace}}
  selector:
    matchLabels:
      component: node
      {{ include "common.labels.standard" . | nindent 6 }}
      {{- include "common.labels.selector" . | nindent 6 }}
      {{- with .Values.node.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}