{{- if .Values.storageClasses }}
{{- range $key, $val := .Values.storageClasses }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ $val.name }}
  namespace: kube-system
  annotations:
    storageclass.kubernetes.io/is-default-class: "{{ $val.defaultStorageClass}}"
provisioner: csi.hetzner.cloud
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: {{ $val.reclaimPolicy }}
---
{{- end }}
{{- end }}