apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cluster-api-controlplane-provider-kubeadm.fullname" . }}-manager
  labels:
    cluster.x-k8s.io/provider: control-plane-kubeadm
  {{- include "cluster-api-controlplane-provider-kubeadm.labels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cluster-api-controlplane-provider-kubeadm.fullname" . }}-controller-manager
  labels:
    cluster.x-k8s.io/provider: control-plane-kubeadm
    control-plane: controller-manager
  {{- include "cluster-api-controlplane-provider-kubeadm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controllerManager.replicas }}
  selector:
    matchLabels:
      cluster.x-k8s.io/provider: control-plane-kubeadm
      control-plane: controller-manager
    {{- include "cluster-api-controlplane-provider-kubeadm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        cluster.x-k8s.io/provider: control-plane-kubeadm
        control-plane: controller-manager
      {{- include "cluster-api-controlplane-provider-kubeadm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args:
        - --leader-elect
        - --metrics-bind-addr=localhost:8080
        - --feature-gates=ClusterTopology=${CLUSTER_TOPOLOGY:=false}
        command:
        - /manager
        image: {{ .Values.controllerManager.manager.image.repository }}:{{ .Values.controllerManager.manager.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        - containerPort: 9440
          name: healthz
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: healthz
        resources: {}
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      serviceAccountName: {{ include "cluster-api-controlplane-provider-kubeadm.fullname"
        . }}-manager
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
      - name: cert
        secret:
          secretName: capi-kubeadm-control-plane-webhook-service-cert