secret:
  name: hetzner
  keyName: hcloud

prometheus:
  serviceMonitor:
    enabled: false
    namespace: "monitoring"
    labels:
      release: prometheus-operator

storageClasses: {}
# - name: hcloud-volumes
#   defaultStorageClass: true
#   reclaimPolicy: Retain

controller:
  replicas: 2

pdb:
  enabled: true
  maxUnavailable: 1