# Default values for csi-hcloud.

common: 
  labels:
    standard: {}
  pod:
    pullSecrets: {}

controller:
  labels: {}
  annotations: {}
  service:
    labels: {}
    annotations: {}
  replicas: 2

pdb:
  enabled: true
  minAvailable: 1

node:
  labels: {}
  annotations: {}
  service:
    labels: {}
    annotations: {}

secret:
  name: hetzner
  keyName: hcloud

storageClasses: {}
# - name: hcloud-volumes
#   defaultStorageClass: true
#   reclaimPolicy: Retain

serviceAccount:
  annotations: {}
  labels: {}

nameOverride: ""
fullnameOverride: ""

nodeSelector: {}

tolerations: []

affinity: {}

prometheus:
  serviceMonitor:
    enabled: false
    namespace: "monitoring"
    labels:
      release: prometheus-operator

