controllerManager:
  manager:
    image:
      repository: k8s.gcr.io/cluster-api/cluster-api-controller
    args:
      machinePool: false
      clusterResourceSet: false 
      clusterTopology: false
  replicas: 1
webhookService:
  ports:
  - port: 443
    targetPort: webhook-server
  type: ClusterIP
