apiVersion: v2
name: capi-cr
description: Helm Chart for deploying a Kubernetes Cluster with the cluster-api.
home: https://github.com/syself/charts/tree/main/charts/capi-cr
type: application
icon: https://cluster-api.sigs.k8s.io/#kubernetes-cluster-apidiv-stylefloat-right-position-relative-display-inlineimg-srcimagesintroductionpng-width160px-div
maintainers:
  - name: Syself
    email: info@syself.com
    url: https://github.com/syself
version: 1.0.5